DROP TABLE IF EXISTS Permission CASCADE;
DROP TABLE IF EXISTS Game CASCADE;
DROP TABLE IF EXISTS LeaguePlayer CASCADE;
DROP TABLE IF EXISTS League CASCADE;
DROP TABLE IF EXISTS Championship CASCADE;
DROP TABLE IF EXISTS Friendship CASCADE;
DROP TABLE IF EXISTS UserProfile CASCADE;
DROP TABLE IF EXISTS Rank CASCADE;
DROP TABLE IF EXISTS Duration CASCADE;
DROP TYPE IF EXISTS WinnerType CASCADE;

CREATE TABLE Duration(
  id SERIAL PRIMARY KEY,
  start_time TIMESTAMP,
  end_time TIMESTAMP
);
CREATE INDEX DurationIndex ON Duration(end_time);

CREATE TABLE Rank(
  id SERIAL PRIMARY KEY,
  name text
);

CREATE TABLE UserProfile(
  id SERIAL PRIMARY KEY,
  nick text,
  first_name text,
  last_name text,
  pwd_hash text,
  rank INT REFERENCES Rank(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  registered TIMESTAMP
);
CREATE INDEX ProfileIndex ON UserProfile(nick);

CREATE TABLE Championship(
  id SERIAL PRIMARY KEY,
  name text,
  duration INT REFERENCES Duration(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Friendship(
  id serial PRIMARY KEY,
  user1 INT REFERENCES UserProfile(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  user2 INT REFERENCES UserProfile(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  duration INT REFERENCES Duration(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX FriendshipIndex ON Friendship(user1);
CREATE INDEX FriendshipIndex2 ON Friendship(user2);

CREATE TYPE WinnerType AS ENUM ('DRAW', 'P1', 'P2');

CREATE TABLE League(
  id SERIAL PRIMARY KEY,
  name text,
  championship INT REFERENCES Championship(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE LeaguePlayer(
  id SERIAL PRIMARY KEY,
  player INT REFERENCES UserProfile(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  league INT REFERENCES League(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  elo INT
);
CREATE INDEX LPIndex ON LeaguePlayer(player);

CREATE TABLE Game(
  id SERIAL PRIMARY KEY,
  player1 INT REFERENCES LeaguePlayer(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  player2 INT REFERENCES LeaguePlayer(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  winner WinnerType,
  duration INT REFERENCES Duration(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX GameIndexP1 ON Game(player1);
CREATE INDEX GameIndexP2 ON Game(player2);
CREATE INDEX GameIndexWT ON Game(winner);
CREATE INDEX GameIndexDur ON Game(duration);

CREATE TABLE Permission(
  id SERIAL PRIMARY KEY,
  name text,
  rank INT REFERENCES Rank(id) ON UPDATE CASCADE ON DELETE RESTRICT
);